### ISSUE TITLE
System  Monitor doesn't show nvme disk devices?

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [mate-desktop/mate-system-monitor#100]
#### Expected behaviour
System Monitor shows all disk activity, including disk nvme devices.

#### Actual behaviour
No disk activity is shown for nvme disk devices.

#### Steps to reproduce the behaviour
* Add System Monitor panel to Mate desktop panel.
* Right click, preferences, enable hard disk monitoring
* Use the disk and notice that disk activity will always be missing

#### MATE general version
Tested and missing versions 1.14.x through 1.18.x

#### Package version
1.18.4

#### Linux Distribution
Debian

#### Link to downstream report of your Distribution
Don't see anything in Debian downstream, since this appears to be an upstream issue. Ubuntu has some users talking about it?

https://ubuntu-mate.community/t/system-monitor-panel-applet/7841

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
Is System Monitor desktop panel disk activity just broken completely since the transition from Gnome classic to Mate?

https://github.com/mate-desktop/mate-system-monitor/issues/95

**Comment by monsta** [comment]
https://github.com/mate-desktop/mate-system-monitor/issues/79

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
https://github.com/mate-desktop/mate-applets/issues/290#issuecomment-348290482
