### ISSUE TITLE
find-as-you-type search should be case-insensitive

### ISSUE THREAD

**Issue by glafream** [mate-desktop/mate-system-monitor#102]
#### Expected behaviour
in Processes tab, if you have the process list focused and begin typing, first matching process should be highlighted without case sensitivity (note: find-as-you-type works correctly (without case sensitivity) in caja)

#### Actual behaviour
find-as-you-type is case-sensitive

#### MATE general version
1.18

#### Package version
1.18.0-1

#### Linux Distribution
Fedora 26

**Comment by monsta** [comment]
Yes, would make sense when searching for VirtualBox's processes, for example.

**Comment by monsta** [comment]
Ok, done in https://github.com/mate-desktop/mate-system-monitor/commit/cd5b3a039d5e7b0d1ca43f7dc703d2d38ab1d477.

**Comment by glafream** [comment]
thanks!
