### ISSUE TITLE
False value in tooltip

### ISSUE THREAD

**Issue by pkzc** [mate-desktop/mate-system-monitor#103]
#### Expected behaviour
One would expect that the processor load tooltip on the graph on the panel shows the actual, real-time value of the measured property and not some value back in the past.

#### Actual behaviour
The processor load tooltip does not show the current CPU load percentage when the cursor is hovered over the graph on the panel. Instead, it shows the value of the left leaving edge of the graph which is 20..30 seconds in the past.
I am not sure about the other graphs and tooltip values, but the memory is also suspicious to me. If I am right on the CPU graph then please check the rest, too.

#### Steps to reproduce the behaviour
1. Run some CPU-intensive program.
2. Shut it down.
3. Hover the cursor over the CPU graph on the panel
4. Observe how the % values change in the tooltip.

#### MATE general version
1.14.1 to 1.18.2

#### Package version
$ rpm -qi mate-system-monitor
Name        : mate-system-monitor
Version     : 1.14.1
Release     : 1.fc24
Architecture: x86_64
Install Date: Thu Aug 25 06:36:50 2016
Group       : Unspecified
Size        : 4491213
License     : GPLv2+
Signature   : RSA/SHA256, Sat Aug 13 18:55:44 2016, Key ID 73bde98381b46521
Source RPM  : mate-system-monitor-1.14.1-1.fc24.src.rpm
Build Date  : Sat Aug 13 00:28:43 2016
Build Host  : buildvm-23.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://mate-desktop.org
Summary     : Process and resource monitor
Description :
mate-system-monitor allows to graphically view and manipulate the running
processes on your system. It also provides an overview of available resources
such as CPU and memory.

#### Linux Distribution
Fedora Linux FC24, FC25

#### Link to downstream report of your Distribution
https://bugzilla.redhat.com/show_bug.cgi?id=1375377

**Comment by raveit65** [comment]
@pkzc 
Thanks for posting this here but it's the wrong project. The panel applet is part of mate-applets.
I will move your infos and call you at mate-applets repo.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-applets/issues/283
