### ISSUE TITLE
please add zfs to default visible filesystems on linux

### ISSUE THREAD

**Issue by bunder2015** [mate-desktop/mate-system-monitor#120]
#### Expected behaviour
being able to see my zfs datasets in the filesystems tab

#### Actual behaviour
empty filesystems tab unless i check "show all filesystems"
available disk space: 0 on system tab 

#### Steps to reproduce the behaviour
use zfs on linux

#### MATE general version
1.20

#### Package version
1.20.2

#### Linux Distribution
gentoo

#### Link to downstream report of your Distribution
not reported to distro

**Comment by SoongNoonien** [comment]
I can confirm this behaviour on Gentoo with MATE 1.22.0.

**Comment by rbuj** [comment]
There is a patch in oi:
https://github.com/OpenIndiana/oi-userland/blob/oi/hipster/components/desktop/mate/mate-system-monitor/patches/01-zfs.patch

**Comment by bunder2015** [comment]
This is a glibtop/zfsonlinux issue unfortunately. 

https://github.com/GNOME/libgtop/blob/master/sysdeps/linux/mountlist.c#L97
```
$ grep zfs /proc/filesystems 
nodev   zfs
```
