### ISSUE TITLE
Supports only 16 CPU's correctly

### ISSUE THREAD

**Issue by SoongNoonien** [mate-desktop/mate-system-monitor#145]
#### Expected behaviour
Being able to set a color for more than 16 processors.

#### Actual behaviour
Mate-system-monitor craches when trying to set the color for CPU 17 or above.
`(mate-system-monitor:5932): GLib-GIO-ERROR **: 11:43:06.401: Settings schema 'org.mate.system-monitor' does not contain a key named 'cpu-color30'`

#### Steps to reproduce the behaviour
1. Take a system with more than 16 CPU's
2. Try to set their color (above 16th CPU)

#### MATE general version
1.22

#### Package version
1.22.0

#### Linux Distribution
Gentoo (also Arch)

#### Link to downstream report of your Distribution
Not reported to any of them.

**Comment by SoongNoonien** [comment]
I just have created a patch which enables mate-system-monitor to set colors for at least 32 processors.

[more-cpus.txt](https://github.com/mate-desktop/mate-system-monitor/files/3076444/more-cpus.txt)

**Comment by raveit65** [comment]
I don't have a AMD Threadripper CPU for testing that, but do a pull request please.
