### ISSUE TITLE
Possible null pointer dereference

### ISSUE THREAD

**Issue by shlyakpavel** [mate-desktop/mate-system-monitor#176]
If `res` is null pointer (that is checked later), then the line
https://github.com/mate-desktop/mate-system-monitor/blob/34df8e288ba50eee95baf8f2d035022e2a113d96/src/openfiles.cpp#L73
Is a null pointer dereference.

**Comment by rbuj** [comment]
getaddrinfo() returns 0 if it succeeds, otherwise an error code.
See RETURN VALUE section on man getaddrinfo.

**Comment by shlyakpavel** [comment]
> getaddrinfo() returns 0 if it succeeds, otherwise an error code.
> See RETURN VALUE section on man getaddrinfo.

But why does the code check for `ret` not to be null right after that?

**Comment by rbuj** [comment]
The variable `res` must be freed if it's not NULL.

https://github.com/mate-desktop/mate-system-monitor/blob/34df8e288ba50eee95baf8f2d035022e2a113d96/src/openfiles.cpp#L77

https://github.com/mate-desktop/mate-system-monitor/blob/34df8e288ba50eee95baf8f2d035022e2a113d96/src/openfiles.cpp#L81
