### ISSUE TITLE
System Monitor report incorrect 'Available' disk size and calculates wrong 'Used%'

### ISSUE THREAD

**Issue by akavalov** [mate-desktop/mate-system-monitor#207]
#### Expected behaviour
I am running System Monitor 3.38.0 on Cinnamon. Not sure this is the right place to report the observation.
System Monitor must report correct 'Available' disk size and calculates correct 'Used%', It is not. 

#### Actual behaviour
System Monitor report incorrect 'Available' disk size and calculates wrong 'Used%'
Please refer to the enclosed snapshots. 
I have two similarly set up mounts, both are btrfs-raid1 with 2 disks over luks. For one of them /home System Monitor shows correct 'Available' value and calculates correct 'Used%'. For the other /mnt/backup it shows Available=0 and Used=100% which is wrong. 

#### MATE general version
I am on Cinnamon. 

#### Linux Distribution
Linux 5.10.9-201.fc33.x86_64 #1 SMP Wed Jan 20 16:56:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
#### Link to bugreport of your Distribution (requirement)
https://bugzilla.redhat.com/show_bug.cgi?id=1919679

![SystemMonitor](https://user-images.githubusercontent.com/59588496/105640053-ed318080-5e49-11eb-9731-c34f326bbbec.png)
![lsblk](https://user-images.githubusercontent.com/59588496/105640056-f589bb80-5e49-11eb-90a0-412c3ac4fc38.png)

**Comment by rbuj** [comment]
Please, submit gnome-system-monitor bugs at https://gitlab.gnome.org/GNOME/gnome-system-monitor/-/issues

**Comment by akavalov** [comment]
Thanks, done here: 
https://gitlab.gnome.org/GNOME/gnome-system-monitor/-/issues/174

**Comment by rbuj** [comment]
however, I was unable to reproduce your problem in either gnome-system-monitor or mate-system-monitor.

![Screenshot at 2021-01-25 11-20-46](https://user-images.githubusercontent.com/10171411/105693560-288e8680-5f00-11eb-8a61-59a427945385.png)

Test: create different/equal files at mount points /mnt/test and /mnt/backup and check the displayed values:
```
head -c 4GB /dev/urandom > /mnt/test/test.txt
head -c 4GB /dev/urandom > /mnt/backup/test.txt
```
```
head -c 4GB /dev/urandom > /mnt/test/test.txt
head -c 2GB /dev/urandom > /mnt/backup/test.txt
```

**Comment by akavalov** [comment]
Thank you, rbuj.

**Comment by akavalov** [comment]
Indeed yours working as expected. This is strange. If someone else reports similar observation - then it will be different story. For now it seems I am the only one having this issue. 
Not sure about "Test: create different/equal files at mount points /mnt/test and /mnt/backup and check the displayed values:". Is this for me to perform the tests, or you describing yours? 
Thanks again.

**Comment by rbuj** [comment]
It's the brief description of the test I performed to reproduce your issue.

**Comment by akavalov** [comment]
Thank you. Appreciated your help. If you ever come across similar complain - please let me know.

**Comment by akavalov** [comment]
I was able to reproduce the bug. I rebuild the btrfs-raid1 over luks. All looked normal until i copied into this directory the SomeBigImage.iso file. System monitor Usage% jumped to 100% although I have free space on the disk.
Hope it helps.
