### ISSUE TITLE
CPU with many cores breaks window layout

### ISSUE THREAD

**Issue by zilent1** [mate-desktop/mate-system-monitor#232]
#### Expected behaviour
Use application normally even when CPU has a great number os cores. Perhaps create a scrollbar on the CPU History below the graph when there are to many cores.
Ability to change the color of any of the shown CPU cores.

#### Actual behaviour
CPU with many cores can (depending on the number of cores) push the lower limit of the window below the lower limit of the screen, and the window can not be resized, so some data (like Network History), can become inacessible.
Also, trying to change the color on any core above 32 (33 -> 128 tested) makes the application close.

#### Steps to reproduce the behaviour
Install a 128-core CPU and open the Resource tab.

#### MATE general version
1.24.0

#### Package version
1.24.0

#### Linux Distribution
Ubuntu 20.04.3 LTS.

#### Link to bugreport of your Distribution (requirement)
https://bugs.launchpad.net/ubuntu/

Related to https://github.com/mate-desktop/mate-system-monitor/pull/147 and https://github.com/mate-desktop/mate-system-monitor/issues/145

![image](https://user-images.githubusercontent.com/7732498/146242446-e2bb266c-861d-4e97-bf77-641c6dca9c45.png)

**Comment by lukefromdc** [comment]
Any way to simulate this on common desktop CPU's, to fake a high core count? A 128 core CPU would be worth as much as most of all of my assets

**Comment by zilent1** [comment]
> Any way to simulate this on common desktop CPU's, to fake a high core count? A 128 core CPU would be worth as much as most of all of my assets
> […](#)
> On 12/15/2021 at 1:20 PM, "zilent1" ***@***.***> wrote: #### Expected behaviour Use application normally even when CPU has a great number os cores. Perhaps create a scrollbar on the CPU History below the graph when there are to many cores. Ability to change the color of any of the shown CPU cores. #### Actual behaviour CPU with many cores can (depending on the number of cores) push the lower limit of the window below the lower limit of the screen, and the window can not be resized, so some data (like Network History), can become inacessible. Also, trying to change the color on any core above 32 (33 -> 128 tested) makes the application close. #### Steps to reproduce the behaviour Install a 128-core CPU and open the Resource tab. #### MATE general version 1.24.0 #### Package version 1.24.0 #### Linux Distribution Ubuntu 20.04.3 LTS. #### Link to bugreport of your Distribution (requirement) https://bugs.launchpad.net/ubuntu/ Related to https://github.com/mate-desktop/mate-system- monitor/pull/147 and https://github.com/mate-desktop/mate-system- monitor/issues/145 ![image](https://user- images.githubusercontent.com/7732498/146242446-e2bb266c-861d-4e97- bf77-641c6dca9c45.png) -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: #232

You could run a VM on QEMU with -smp 64 or more. From what I've read QEMU allows you to emulate more cores than phisically available, however performance isn't that great.

I'll see if I can get some time to test https://github.com/mate-desktop/mate-system-monitor/pull/233 tomorrow, it seems it might do the trick.

**Comment by lukefromdc** [comment]
Sorry, I won't be able to do that as I have literally never worked with VM's. Others on the team do however, so they might be able to use this method to test
