### ISSUE TITLE
changes make to process preferences are reverted the next time open system monitor

### ISSUE THREAD

**Issue by linuxgirl22** [mate-desktop/mate-system-monitor#234]
#### Expected behaviour
That preferences constant across sessions and not removed.

#### Actual behaviour
Change which columns are viewed, but, next time open system monitor, changes are reverted.

#### Steps to reproduce the behaviour
Open system monitor, make changes in Preferences/Processes. Close system monitor. Re-open and changes are gone. 

#### MATE general version
1.26.0-1

#### Package version
1.26.0-1

#### Linux Distribution
Sparkylinux

#### Link to bugreport of your Distribution (requirement)
No point in bothering them with this, as this issue only happens since upgrade to Mate 1.26.0-1 yesterday. Sparkylinux have no involvement in that. 

On trying to find a config, I so far saw there is a system.3.gz ... I tried extracting that, but the system.3 is too complex to understand. Is there a simple config anywhere, in which to save changes? Concerned that this is one of the parts of Mate that has had wayland support added, and that changes are deliberately reverted, with, so far, no easy way to block that. If this applies to any part of Mate that's been adapted to wayland, I will have to look to another desktop.

**Comment by mbkma** [comment]
does https://github.com/mate-desktop/mate-system-monitor/commit/ddeb66b5af61a5367c8b72a5e5845317e82b62a4 fix your problem? This patch should be included in the next point release.

**Comment by raveit65** [comment]
> does ddeb66b fix your problem? This patch should be included in the next point release.

+1 for merging the commit into 1.26 and closing this report.

**Comment by mbkma** [comment]
@linuxgirl22 Wayland is not delivered with MATE, nor does MATE officially have Wayland support. It is only that some of our applications got Wayland support, which means they run on Wayland and on X11. There should nothing stop you from running MATE 1.26. Everything should work on X11 absolutely fine. Most commits to support Wayland are of the form:
```c
if (on wayland) do this
else do that
```
so there is nothing really to worry about.

**Comment by linuxgirl22** [comment]
Thanks for your assurances, but unfortunately wayland did cause issues with running my X11 desktop properly ... the sysmon issue, and freefilesync had odd errors, and that was just after a fresh install and the initial updates which included 1 26. No issues with freefilesync on reinstalling and locking at 1 24. Also, seeing that config files appear to need the unzipping/re-zipping of a file from a very large folder of zipped files concerned me a lot. I don't want a desktop that's constantly transitioning things to wayland, throwing up issues, or runs anything wayland.

**Comment by colibris79** [comment]
@mbkma same problem here with Mint 21, and mate-system-monitor 1.26.0-1. Tried to install the github version but got some dependencies error. Any other way to apply the patch?
```
configure: error: Package requirements (
    glib-2.0 >= 2.56.0
    libgtop-2.0 >= 2.37.2
    gtk+-3.0 >= 3.22.0
    gtkmm-3.0 >= 3.8.1
    libxml-2.0 >= 2.0
    librsvg-2.0 >= 2.35
    glibmm-2.4 >= 2.22
    giomm-2.4 >= 2.26.0
    gmodule-2.0
) were not met:

No package 'glib-2.0' found
No package 'libgtop-2.0' found
No package 'gtk+-3.0' found
No package 'gtkmm-3.0' found
No package 'libxml-2.0' found
No package 'librsvg-2.0' found
No package 'glibmm-2.4' found
No package 'giomm-2.4' found
No package 'gmodule-2.0' found
```
Thanks

**Comment by mbkma** [comment]
to install the Github version on Linux Mint/Debian/Ubuntu:
1. `sudo apt build-dep mate-system-monitor`
2. `./autogen.sh --prefix=/usr`
3. `make`
4. `sudo make install`

Be careful though, this might lead to instabilities and reverting back to the old version is not always that easy.

**Comment by colibris79** [comment]
> to install the Github version on Linux Mint/Debian/Ubuntu:
> 
> 1. `sudo apt build-dep mate-system-monitor`
> 2. `./autogen.sh --prefix=/usr`
> 3. `make`
> 4. `sudo make install`
> 
> Be careful though, this might lead to instabilities and reverting back to the old version is not always that easy.

Thanks for the reply. Then should I better wait for the official release?

**Comment by mbkma** [comment]
Yes, if the fix is not absolutely necessary for you.
