### ISSUE TITLE
Dconf proctree column shift

### ISSUE THREAD

**Issue by Mezalor** [mate-desktop/mate-system-monitor#243]
I have an issue when I try to modify the GUI of mate-system-monitor 1.26 (there is no problem with 1.24) with dconf. This is probably the same problem as #242 
Specifically this is a problem with proctree columns. I think a column disappeared between version 1.24 and 1.26 since there is a shift from column 5 or 6. For example
```
[org/mate/system-monitor/proctree]
col-0-visible=true
col-1-visible=true
col-2-visible=true
col-3-visible=false
col-4-visible=false
col-5-visible=false
col-6-visible=false
col-7-visible=false
col-8-visible=false
col-9-visible=false
col-10-visible=true
col-11-visible=false
col-12-visible=false
col-13-visible=false
col-14-visible=false
col-15-visible=false
col-16-visible=false
col-17-visible=false
col-18-visible=false
col-19-visible=false
col-20-visible=false
col-21-visible=false
col-22-visible=false
col-23-visible=false
col-24-visible=false
col-25-visible=false
col-26-visible=false
columns-order=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
sort-col=0
sort-order=0
```
displays column "Nice" (col-11) instead of the column "Started" (col-10)

**Comment by rbuj** [comment]
In the quick test I performed, everything works correctly: After disabling "Nice" column in "System Monitor Preferences" dialog:
```
$ dconf dump /org/mate/system-monitor/proctree/
[/]
col-11-visible=false
```
col-11-visible is the 11th element in [1], zero-based numbering:
 https://github.com/mate-desktop/mate-system-monitor/blob/2b767be06f5b5b602e56740275784bb9bf3474c3/src/proctable.cpp#L264

**Comment by Mezalor** [comment]
When the application is launched I don't actually have the issue. But when I close the application and restart it, it seems that there is a shift between the parameters given in dconf and what is actually displayed . For example if I close mate-system-monitor and I do
```
$ dconf load / << EOF
[org/mate/system-monitor/proctree]
col-10-visible=false
col-11-visible=true
col-12-visible=false
EOF
$ mate-system-monitor
```
then the wrong column is displayed.

**Comment by rbuj** [comment]
I reproduced the issue using `--disable-wnck`, and #224 fixed it, since the index COL_MEMXSERVER must be avoided.
```
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CXX=clang++ CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum --disable-wnck && make &> make.log && sudo make install
```
