### ISSUE TITLE
Processes tab - Fails to save "Information fields" preferences.

### ISSUE THREAD

**Issue by BusterKnutt** [mate-desktop/mate-system-monitor#245]
#### Expected behaviour
Program saves my settings between restarts.

#### Actual behaviour
Fails to save my settings in the Processes tab only.  All others stick.
Resets to showing the following fields:
Process Name
Status
%CPU
CPU Time
Waiting Channel

#### Steps to reproduce the behaviour
Edit "Processes" preferences and change some values in the "Information Fields".
Close and restart Mate-System-Monitor
Your changes have gone. 

#### MATE general version
1.26

#### Package version
1.26.0-1

#### Linux Distribution
Linux Mint

#### Link to bugreport of your Distribution (requirement)

Can't find an option to report the bug on the Mate website.  They don't post a link...

**Comment by mikilopez** [comment]
Same problem here. Same MATE version in Manjaro. The defaults are different from @BusterKnutt ones, though.
I also noticed that when I add columns, and change their width, when restarting the columns are lost but the width of the "default" columns are weird. Most obvious when I add "command line" column, make it super wide, and when restarting my "Memory" column is the one getting super wide.

**Comment by mbkma** [comment]
You could try if applying this patch helps. We will release version 1.26.1 with this patch included soon.

**Comment by BusterKnutt** [comment]
A little light bash scripting is the limit of my programming knowledge.  I have no idea what to do with that linked text.
I shall wait for the update to hit the repo.
Thanks, mbkma

**Comment by mbkma** [comment]
I'll leave this open until 1.26.1 is released...

**Comment by okfruit** [comment]
debian 12 has the same problem.

**Comment by mikilopez** [comment]
Manjaro updated to MATE 1.26.1 and the problem persists

**Comment by mesov** [comment]
This is happening only if I try to change the visibility of any field beyond "X Server Memory" (field number 7 in dconf).
"X Server Memory" is not listed as a process information field in the Preferences window. 

If applicable, any change to one of those fields is in fact applied to the next field after restart, probably because the numbering in the System Monitor is one field ahead from field 7 on.

**Comment by mesov** [comment]
Applying the [patch](https://github.com/mate-desktop/mate-system-monitor/issues/245#issuecomment-1300064893) in 1.26.0 fixed it downstream:

https://gitlab.trisquel.org/trisquel/package-helpers/-/commit/f75431198ce84e876c409946696b4f0fba94dd17

**Comment by raveit65** [comment]
It's now in 1.26 branch.
https://github.com/mate-desktop/mate-system-monitor/commit/83bd2793a7f660af3231eded3986cf622057baa3

**Comment by raveit65** [comment]
1.26.1 is released https://github.com/mate-desktop/mate-system-monitor/releases/tag/v1.26.1
Closing...
