### ISSUE TITLE
meson: translations in help not built

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/mate-system-monitor#249]
#### Expected behaviour
```
meson build --prefix /usr 
ninja -C build
sudo ninja -C build install 
```
 
builds and installs package with same translations in help directory (installs to /usr/share/help)

#### Actual behaviour
```
meson build --prefix /usr 
ninja -C build
sudo ninja -C build install 
```
does not install any translations in help, only the C directory
locales still get installed
This turned out to be the case on every package of mate-system-monitor I have ever built with meson but just noticed
it now as I do not use the translations, but saw a big reduction in installed package size.

#### Steps to reproduce the behaviour
We will be using the /usr/share/help/af directory here simply because it is the first directory in /usr/share/help and is
easily found

1: remove your normal mate-system-monitor install, be sure  /usr/share/help/af/mate-system-monitor is removed
2: Build and install with autotools, look for directory /usr/share/help/af/mate-system-monitor it will be installed
3: uninstall this build
4: Build and install with meson, /usr/share/help/af/mate-system-monitor is not installed so does not show up
5: Cleanup: uninstall and install whatever package you are using for mate-system-monitor

#### MATE general version
1.27.0 from git master

#### Package version
local build

#### Linux Distribution
Debian Unstable last updated 3-26-2023

#### Link to bugreport of your Distribution (requirement)
None as this is a local build

**Comment by zhuyaliang** [comment]
@lukefromdc Fixed, please test PR code
