### ISSUE TITLE
wayland: application not shown in menu on mate-panel

### ISSUE THREAD

**Issue by Sunderland93** [mate-desktop/mate-system-monitor#252]
#### Expected behaviour
`mate-system-monitor` should displayed in applications menu

#### Actual behaviour
`mate-system-monitor` does not displayed in menu until I delete the line `OnlyShowIn=MATE;` in `mate-system-monitor.desktop` file

#### Steps to reproduce the behaviour
1) build mate-panel with Wayland support
2) open applications menu and select "System" category

#### MATE general version
1.26.0

#### Package version
1.27.0

#### Linux Distribution
Debian 12

#### Link to bugreport of your Distribution (requirement)
n/a

**Comment by Sunderland93** [comment]
I'm not sure that I write this issue in a right place, but removing `OnlyShowIn=MATE;` fixed this issue for me.

**Comment by raveit65** [comment]
Not  a bug, OnlyShowIn=Mate is the behavior that we want.
In fedora 38 mate-system-monitor displays fine in menus inside a **mate session** when panel is compiled with wayland support.

**Comment by lukefromdc** [comment]
That is because in wayland we are not currently running in a MATE session, thus` OnlyShowIn=Mate` excludes it from the menu. That will need to be part of a wayland mate session, we can probably handle this one the same way GNOME did

**Comment by Sunderland93** [comment]
Ah, yes. `export XDG_CURRENT_DESKTOP=MATE` also solves this issue
