### ISSUE TITLE
German tab header translation wrong

### ISSUE THREAD

**Issue by muesli4** [mate-desktop/mate-system-monitor#257]
#### Expected behaviour

The translation should be at the correct location.

#### Actual behaviour

![screenshot](https://github.com/mate-desktop/mate-system-monitor/assets/2077630/d3effd4d-63f7-48c9-8735-f04338a4e472)
The translation present in the tab header seems unlikely to be correct.  I do not know whether someone maliciously tinkered with the translations or it is just a mix-up.  ~But I cannot find the corresponding translation on transifex.~

#### Steps to reproduce the behaviour

Start `mate-system-monitor` with German translation.

#### MATE general version

1.26.2

#### Package version

1.26.1-1

#### Linux Distribution

Arch Linux

#### Link to bugreport of your Distribution (requirement)

There is none.  But the package is also not modified by the distribution.  See here: https://gitlab.archlinux.org/archlinux/packaging/packages/mate-system-monitor/-/blob/main/PKGBUILD

**Comment by raveit65** [comment]
Is the translation error at transifex? 
https://app.transifex.com/mate/MATE/dashboard/

**Comment by muesli4** [comment]
Now I found it.  It is in 1.26 translation: https://app.transifex.com/mate/MATE/translate/#de/1-26--mate-system-monitor/333896346?q=text%3AResources

**Comment by raveit65** [comment]
Confirmed! Translation with 1.26.0 was `Ressourcen`.

**Comment by raveit65** [comment]
Fixed at transifex.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-system-monitor/commit/596eafb933b15376a52fc4ddb975be49709edade

**Comment by raveit65** [comment]
Hmm, using this as patch for package building doesn't update the wrong translation.
Looks like we need a new release to update *.gmo files.

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-system-monitor/releases/tag/v1.26.2
