### ISSUE TITLE
Italian tab header translation wrong (and probably others)

### ISSUE THREAD

**Issue by svavassori** [mate-desktop/mate-system-monitor#258]
With a recent update 1.26.2, I noticed the Italian translation of "Resources" tab is wrong, while on the previous 1.26.0 is correctly translated.

**Expected behavior**
![msm-1 26 0-1](https://github.com/mate-desktop/mate-system-monitor/assets/1374430/c3c585a1-74e5-4a1d-b9f2-9a1731543b3d)

**Actual behavior**
![msm-1 26 2-1](https://github.com/mate-desktop/mate-system-monitor/assets/1374430/7c5f21be-c7c0-41b6-882a-ebb25d2c53d6)

**Steps to reproduce the behavior**
Start mate-system-monitor with Italian translation.

**MATE general version:** 1.26.2
**Package version:** 1.26.2-1
**Linux Distribution:** Debian testing

This is exactly the same problem that happened with the German translation in #257
Moreover, by looking at other translations in that [change](https://github.com/mate-desktop/mate-system-monitor/commit/b6f2cfb0f443f0164c91cf6775ab04a60c527724) it seems there are other 6 that are wrong:

- [Spanish](https://github.com/mate-desktop/mate-system-monitor/blob/v1.26.2/po/es.po#L523) (probable, not 100% sure)
- [Greek](https://github.com/mate-desktop/mate-system-monitor/blob/v1.26.2/po/el.po#L501)
- [French](https://github.com/mate-desktop/mate-system-monitor/blob/v1.26.2/po/fr.po#L541)
- [Italian](https://github.com/mate-desktop/mate-system-monitor/blob/v1.26.2/po/it.po#L517)
- [Polish](https://github.com/mate-desktop/mate-system-monitor/blob/v1.26.2/po/pl.po#L538)
- [Portuguese](https://github.com/mate-desktop/mate-system-monitor/blob/v1.26.2/po/pt.po#L525)

**Comment by raveit65** [comment]
Fixed at transifex translation tool.
https://github.com/mate-desktop/mate-system-monitor/commit/ec8de20d163033382e797b308b60f35428cc6a8e
And a new release.
https://github.com/mate-desktop/mate-system-monitor/releases/tag/v1.26.3
