### ISSUE TITLE
meson.build files are not in released 1.28 tarball generated with distcheck

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-system-monitor#260]
#### Expected behaviour
Working releasing with travis-ci

#### Actual behaviour
Meson.build files are missing

#### Steps to reproduce the behaviour

Check released tarball https://github.com/mate-desktop/mate-system-monitor/releases/tag/v1.28.0
#### MATE general version

1.28
#### Package version
1.28.0

**Comment by raveit65** [comment]
@mate-desktop/core-team

**Comment by lukefromdc** [comment]
https://github.com/mate-desktop/mate-system-monitor/pull/261 works fine, just tested it

**Comment by raveit65** [comment]
https://github.com/mate-desktop/mate-system-monitor/commit/7913635b26b16e8ce6385ab3eed513b8e64d9a98 is merged
