### ISSUE TITLE
System monitor (and netspeed applet) doesn't measure network traffic correctly

### ISSUE THREAD

**Issue by Zero3** [mate-desktop/mate-system-monitor#38]
Just installed Linux Mint 17 Qiana and noticed that neither the system monitor nor the netspeed applet measure network traffic correctly. It only ever shows a few bytes or kilobytes per second (which appears to be loopback traffic) no matter the actual usage. I can watch a YouTube video, stream from Twitch and download a 100 MB file from my VPS at the same time without any traffic usage according to both tools.

Is this a known problem, or is there anything I can do to help debug it?

**Comment by monsta** [comment]
Does it still happen in Mint 17.3, or maybe 18?

**Comment by Zero3** [comment]
No idea. I no longer use the setup that I used 2 years ago (!) when I reported this issue. So I'm afraid I can't answer your question.
