### ISSUE TITLE
mate-system-monitor "hangs", if there's no network traffic to show

### ISSUE THREAD

**Issue by msteudtn** [mate-desktop/mate-system-monitor#42]
Hello,

following "Problem" / Situation:

I have a rather instable network-connection and the panel-applet of the mate-system-monitor running. If the Internet connection goes down (while wifi stays connected) the system-monitor hangs for a while until there's some network-traffic to monitor again.

Depending on my Internet service provider this can take some seconds or minutes. During this time the applet in the panel isn't moving / reacting.

I first noticed it on the panel (while ping-ing in the background) but I guess it should happen with the system-monitor, too.

System Environment:
- Linux Mint 17 (Kernel 3.13)
- MATE 1.8.1

thanks!
##

**Comment by flexiondotorg** [comment]
I can't reproduce on Ubuntu MATE 17.04 with MATE 1.17 or Ubuntu MATE 16.04 with MATE 1.16. If this issue still exists please re-open.
