### ISSUE TITLE
m-s-m only shows 32 CPU cores

### ISSUE THREAD

**Issue by sunweaver** [mate-desktop/mate-system-monitor#55]
I have just noticed on a 40core system, that mate-system-monitor only shows 32 CPUs...

Greets,
Mike
##

**Comment by monsta** [comment]
Turned out it was a limitation of libgtop, they only supported 32 CPUs.
Fixed in libgtop 2.30 with this commit:
https://git.gnome.org/browse/libgtop/commit/?id=efaaf6eb77e01f1ea002c19a261e4f3ac4788d25

**Comment by bdejean** [comment]
Hello,

I'm libgtop upstream and it really needs a fix. I'll make it next week.

**Comment by monsta** [comment]
Ah, you mean the dynamic number of CPUs (https://bugzilla.gnome.org/323354)?
