### ISSUE TITLE
Add two tabs in System monitor

### ISSUE THREAD

**Issue by mauricejl** [mate-desktop/mate-system-monitor#58]
Hi, 
In base LM mate, it's not useful to know the hardware 
The idea is to add one tab for the pci and one tab for the usb.
Tell me if it needs to use a different way to push this suggestion.

Thanks a lot for your contribution in LinuxMint !

Jean-Luc

**Comment by monsta** [comment]
Any ideas what would be monitored in these tabs? If you just want a static info about devices, simply use ```hardinfo``` tool.

**Comment by mauricejl** [comment]
Hello,
As OS (windows, whatever the version) installed on many, many computers, we
can find the hardware informations in System properties.
To give to LM users the same approch, easy approch, I think we have to find
the useful informations (like hardware, usb, LM version, memory. running
processes) in the same program.
System monitor is very good graphical program so it would be logical to
find hardware tab and usb tab in this program.
And this without install an another program, like hardinfo.

Do you use hardinfo, it don't work very well ? On my computer there is
nothing in usb view ......
and there are so many options..... Unusfull options for many users

Is it possible to give a graphical view of lspci and lsusb commands ?

That's just an idea....

Regards

JL

**Comment by monsta** [comment]
So I see no real suggestion which *changes* would be monitored in these tabs. No surprise. There's virtually nothing to monitor.
