### ISSUE TITLE
memory display error

### ISSUE THREAD

**Issue by ChaoMai** [mate-desktop/mate-system-monitor#60]
here is the problem:

![default](https://cloud.githubusercontent.com/assets/1412813/10410650/d2e44c1c-6f7a-11e5-9a03-4d68e367eab6.PNG)

but obviously I don't have some much memory.

environment: archlinux, mate-system-monitor 1.10.1-1

**Comment by Deuchnord** [comment]
Same problem here, with Arch Linux and `mate-system-monitor` 1.10.1-1` too.

**Comment by maandree** [comment]
I am also experiencing this. Same spec:s here.

Appears on almost all processes that I own (are not
owned by root (do not know if that matters.)) The
displayed memory usage of these processes is very
volatile, and can change a couple of ZiB every update.

**Comment by ChaoMai** [comment]
![image](https://cloud.githubusercontent.com/assets/1412813/10517713/98de6c68-7390-11e5-8346-60ede4003e38.png)

@maandree Yes, it seems that the issue only appears on user's processes. Others' are fine.

**Comment by maandree** [comment]
Should add that it is the writable memory (and hence also "memory") that messed up. Other users' processes the writable memory appears to be "N/A" (why "memory" looks fine for other users.)

**Comment by Chootin** [comment]
Same issue here, version 1.10.1 running on Arch Linux.

**Comment by muesli4** [comment]
Can confirm. It's been there for a while, but I feel not longer than a year, so it must be something introduced recently.

**Comment by raveit65** [comment]
i can' t confirm this for fedora, maybe a distro issue?

**Comment by muesli4** [comment]
Probably, I'm also running Arch. But as I said, everything is fine, when I compile the git-version by myself.

**Comment by Deuchnord** [comment]
My installation comes from Arch's official repositories, so I guess this issue is not only related to the Git version :/

**Comment by muesli4** [comment]
Have you compiled the git-version, or why are you saying that? For me there is **no** issue with it!

**Comment by Deuchnord** [comment]
Sorry, didn't read your last message correctly, I read that you got the same problem by compiling the Git version, you're right ^^

**Comment by plaguewolf** [comment]
dat address sanitizer

https://en.wikipedia.org/wiki/AddressSanitizer

"The Linux kernel has enabled the AddressSanitizer for the x86-64 architecture as of Linux version 4.0. The kernel instrumentation requires a special feature in the compiler suppling the -fsanitize=kernel-address command line option, since kernels do not use the same address space as normal programs."

**Comment by plaguewolf** [comment]
sooo.....?

any clues? what should be done?

id like to have a working system monitor.

**Comment by muesli4** [comment]
Talk to the package maintainer to ship the git version or build it yourself and package it.

**Comment by plaguewolf** [comment]
oh, i see. its one of those things. i guess i'll give it a try with building the git version.

who exactly is the package maintainer?

**Comment by plaguewolf** [comment]
well how about that. compiled easy as pie, and now showing proper ram info.

**Comment by plaguewolf** [comment]
hmmmm. maybe not; http://i.imgur.com/OlXyrSF.png

htop says 1.8GB, mate-system-monitor says 4.6GB.

im inclined to believe htop over MSM.

**Comment by xpander69** [comment]
confirming, same issue
Arch x86_64, mate-system-monitor 1.10.1-1

**Comment by kstripp** [comment]
Confirming same issue, but on Debian, not arch.

Debian Sid x86_64, mate-system-monitor 1.10.1

**Comment by xpander69** [comment]
seems to be fixed in mate-system-monitor 1.12

**Comment by maandree** [comment]
The issue is fixed in version 1.12.

**Comment by Deuchnord** [comment]
Fixed here with version 1.12 too.

**Comment by flexiondotorg** [comment]
Thanks for the feedback guys.
