### ISSUE TITLE
Gtk3: reducing the size of first column to zero in device tap closes the application

### ISSUE THREAD

**Issue by raveit65** [mate-desktop/mate-system-monitor#62]
this is with gtk+-3.16

**Comment by monsta** [comment]
Interesting, I can't reproduce it with 3.14 but I recall I could do so with 3.16.

**Comment by monsta** [comment]
It's kind of random... I can't reproduce it every time.

The backtrace is quite big: http://pastebin.com/hWZ4JFa5

**Comment by monsta** [comment]
Randomly reproducible with 3.14 as well... dammit :confused:

**Comment by raveit65** [comment]
Well, if i compare it with process tap it should not be possible to reduce the size to zero,
looks like this is the issue.

**Comment by raveit65** [comment]
It's possible to reorder any other column as first column.
But those columns doesn't have the prob.

**Comment by raveit65** [comment]
Ok, this line is missing in our code
https://git.gnome.org/browse/gnome-system-monitor/tree/src/disks.cpp#n410
I will try this out.

**Comment by raveit65** [comment]
Hmm, those line comes from https://git.gnome.org/browse/gnome-system-monitor/commit/?h=gnome-3-8&id=f589439a966151b2589bca21a4d6b40455eb201a
Don't know if this is related.
As a workaround we can set 
gtk_tree_view_column_set_resizable(col, FALSE);

**Comment by raveit65** [comment]
Opps, i noticed you did partially use this commit for another PR.
Why not trying to use the rest too?

**Comment by raveit65** [comment]
It looks that the issue is in GtkCell.
Using not a horizontal padding 0 or not to set this value in themes can cause this crash.
Ie. BlueMenta
https://github.com/mate-desktop/mate-themes/blob/master/desktop-themes/BlueMenta/gtk-3.0/gtk-widgets.css#L3969
Ican fix that with adding this to mate-application.css
```
/* workaround for crash if reducing the size of device column to zero,
   horizontal padding needs to set to 0, any other value crashes m-s-m */

.notebook .vertical GtkScrolledWindow GtkTreeView .cell {
	padding: 1px 0px 0px 0px;
}
```
I will add this to all themes.

**Comment by raveit65** [comment]
@monsta 
not shure if we can consider this issue as fixed,
Up to you :)
fixing it with our themes is sufficient for me ;)

**Comment by monsta** [comment]
We need to set minimal column width...
