### ISSUE TITLE
mate-system-monitor not starting on debian jessie

### ISSUE THREAD

**Issue by platschi** [mate-desktop/mate-system-monitor#76]
```
platschi@platschi:~$ mate-system-monitor 
**
ERROR:proctable.cpp:135:void proctable_set_columns_order(GtkTreeView*, GSList*): assertion failed: (id >= 0 && id < NUM_COLUMNS)
Aborted
```

It opens with `sudo`, however I don't know if that's the purpose.

System: Debian 8.2 (jessie)
MATE 1.8.1

**Comment by raveit65** [comment]
Downstream report about?
@sunweaver

**Comment by monsta** [comment]
Please post the output of:
```
gsettings get org.mate.system-monitor.proctree columns-order
```
```
gsettings get org.mate.system-monitor.disktreenew columns-order
```

**Comment by platschi** [comment]
<pre>platschi@platschi:~$ gsettings get org.mate.system-monitor.proctree columns-order
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

platschi@platschi:~$ gsettings get org.mate.system-monitor.disktreenew columns-order
[0, 1, 2, 3, 4, 5, 6]</pre>

**Comment by monsta** [comment]
Oh, 22 is too much for 1.8.x versions. By any chance, did you upgrade to 1.10 at some point and then reverted it back?

**Comment by monsta** [comment]
Fixed in master and 1.12.

@flexiondotorg @sunweaver please make a patch for Jessie out of https://github.com/mate-desktop/mate-system-monitor/commit/e53331f921a05d7d130fe3f494c3594a8ef1b5e0.

**Comment by ikatza** [comment]
I'm experiencing this issue on a fresh install of Debian Jessie (coming from Testing). Where can I get the patch? is there another workaround?

**Comment by caveman-dick** [comment]
I'm getting this on LinuxMint 17

I managed to get this to load by manually changing the value using the following command-line:

`gsettings set org.mate.system-monitor.proctree columns-order "[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]"`

The window now shows however the first load took an age to load but now it's working fine! :tada:

**Comment by ikatza** [comment]
Hey great that did it! And it didn't took long to open either. Thanks.
