### ISSUE TITLE
Unable to show disk graph for NVME

### ISSUE THREAD

**Issue by shorawitz** [mate-desktop/mate-system-monitor#79]
I can't figure out how to enable the graph (Monitored Resources) for "Harddisk" for a NVME SSD.  I can check the box, but no data is displayed (read/write.)  I'm wondering if it's just a path issue (i.e. system-monitor is looking for sdX | hdX or if the NVME just doesn't report the needed data or at least not the default way.

System Monitor is able to show the usage, but the performance graph is broken.

O/S: Mint 17.3 Mate
System Monitor: 1.12.0

Let me know if I can provide any other info to help diagnose this issue.
##

**Comment by flexiondotorg** [comment]
What monitoring application are you using? Can you provide a screenshot? I can't find anything like what you're describing in `mate-system-monitor` nor `gnome-system-monitor`. I do see an NVME drive in both on Ubuntu 1604 and Ubuntu MATE 16.04 however.

**Comment by shorawitz** [comment]
The application is "System Monitor 1.12.1.  I use this app in my panel to monitor CPU, memory, network activity and previously disk activity.  It used to work w/Mint Mate prior to release 17.x (not sure when it actually stopped.)  Now I exclusively use Ubuntu Mate 16.04 with the panel including the monitor applet.

I've attached a screen capture of the monitor and preferences.  At the time of the screen capture, I was testing the drive I/O using 'dd' .

![panel_meter](https://cloud.githubusercontent.com/assets/161034/22069363/6cae5f60-dd55-11e6-968b-4a1482121751.png)

**Comment by leigh123linux** [comment]
@shorawitz I believe you misfiled your report.

https://github.com/mate-desktop/mate-sensors-applet/issues

**Comment by raveit65** [comment]
It's https://github.com/mate-desktop/mate-applets/tree/master/multiload

**Comment by monsta** [comment]
Indeed, this is an applet from mate-applets repo. Please create a new report there because github doesn't allow us to move reports between repos.

**Comment by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [comment]
https://github.com/mate-desktop/mate-applets/issues/290#issuecomment-348290482
