### ISSUE TITLE
Incorrect “available disk space”

### ISSUE THREAD

**Issue by maandree** [mate-desktop/mate-system-monitor#84]
Under System → System status, “Available disk space” shows 195.1 GiB.
This value does not show up in `df` or in File Systems, and it is definitely not a sum.
Additionally, neither 181.7 or 209.5 (195.1⋅10⁹/2³⁰ and 195.1⋅2³⁰/10⁹) show up in any list.
##

**Comment by flexiondotorg** [comment]
I can't reproduce this. `df -h` and `mate-system-monitor` both report the same amount of available disk space. This was tested using `mate-system-monitor` 1.17 and 1.16.

**Comment by maandree** [comment]
But does the System tab report any value reported in the File Systems tab?

**Comment by maandree** [comment]
I figured it out. It is the sum of some, but not necessarily all, mount's available space. This includes bind-mounts. Mounts under /media seem to be excluded (but I don't know what causes the exclusion). I'm happy with this, so unless you want to change this, feel free to close the issue.
