### ISSUE TITLE
ADD option to show numeric values in applet

### ISSUE THREAD

**Issue by allanlaal** [mate-desktop/mate-system-monitor#91]
### use case:

I need to quickly glance at how much free memory I have.
Currently it is difficult to tell the exact amount from the applet by using colors only

**Comment by monsta** [comment]
This repository doesn't contain any applets. The applet is called "multiload" and is a part of [mate-applets](https://github.com/mate-desktop/mate-applets). If you still have the problem, please file a new report there. It's not possible to move reports between repositories.
