### ISSUE TITLE
"System" logo is misaligned

### ISSUE THREAD

**Issue by mrnhmath** [mate-desktop/mate-system-monitor#93]
#### Expected behaviour
The logo should be properly aligned ![aaaaaa](https://user-images.githubusercontent.com/13562431/28341619-e510706e-6bea-11e7-88ac-2ef93db9d938.png)

#### Actual behaviour
The logo is misaligned ![aaaa](https://user-images.githubusercontent.com/13562431/28341626-eb7f0fb4-6bea-11e7-872c-583e329939ad.png)

#### Steps to reproduce the behaviour
Open System Monitor and go to "System" tab

#### MATE general version
1.18.0

#### Package version
1.18.0

#### Linux Distribution
Arch

**Comment by raveit65** [comment]
Confirmed in fedora 26.
Weird, gtk3-inspector says it is a missing xpad/ypad values from GtkMisc.
But we don't use GtkMisc here at this point as it is deprecated.
Looks like there is an issue with cairo which seems to be ignore those defines.
https://github.com/mate-desktop/mate-system-monitor/blob/master/src/sysinfo.cpp#L628

**Comment by mrnhmath** [comment]
After a system update (gtk?) the logo is now properly aligned. Can anyone else confirm?
![captura de tela em 2017-10-07 18-40-16](https://user-images.githubusercontent.com/13562431/31312010-5c38ef16-aba8-11e7-81ec-766f17c27a9d.png)

**Comment by raveit65** [comment]
Not here, gtk version is gtk3-3.22.21-1.fc26.x86_64,
Maybe cairo was updated?
cairo-1.14.10-1.fc26.x86_64

**Comment by monsta** [comment]
@mrnhmath: check the fix at https://github.com/mate-desktop/mate-system-monitor/pull/105.
